# Mitch Gavars
# Professor Marchiori
# CSCI 315 Prelab 2 Makefile
# 9/09/19

CC = gcc
CFLAGS = -std=gnu99 -Wall -g 

heap-test: heap-test.c
	$(CC) $(CFLAGS) heap-test.c -o heap-test

pipe-test: pipe-test.c
	$(CC) $(CFLAGS) pipe-test.c -o pipe-test
