# Mitch Gavars
# Professor Marchiori
# CSCI 315 Lab3 Makefile
# 9/17/19

CC = gcc
CFLAGS = -std=gnu99 -lpthread -lm -Wall -g 

summation: summation.c
	$(CC) $(CFLAGS) summation.c -o summation

summation3: summation3.c
	$(CC) $(CFLAGS) summation3.c -o summation3

mytime: mytime.c
	$(CC) $(CFLAGS) mytime.c -o mytime

summation4: summation4.c
	$(CC) $(CFLAGS) summation4.c -o summation4
