# Mitch Gavars 
# Professor Marchiori 
# CSCI 315 Lab6 Makefile 
# 10/08/19

CC = gcc 
CFLAGS = -std=gnu99 -lpthread -lm -Wall -g -DDEBUG

dp: dp.c
	$(CC) $(CFLAGS) dp.c -o dp

problem1: problem1.c
	$(CC) $(CFLAGS) problem1.c -o problem1

