# Mitch Gavars
# CSCI315 Lab1 - Makefile
# Alan Marchiori
# 9/3/19

CC = gcc
CFLAGS = -std=gnu99 -Wall -g #DEBUG

cmds: cmds.c
	$(CC) $(CFLAGS) cmds.c -o cmds

cmdreverse: cmdreverse.c
	$(CC) $(CFLAGS) cmdreverse.c -o cmdreverse

myprog: myprog.c
	$(CC) $(CFLAGS) myprog.c -o myprog 

fork: fork.c
	$(CC) $(CFLAGS) fork.c -o fork
