# Mitch Gavars
# Professor Marchiori
# CSCI 315 Lab4 Makefile
# 9/24/19

CC = gcc
CFLAGS = -std=gnu99 -lpthread -lm -Wall -g 


echoreq: echoreq.c
	$(CC) $(CFLAGS) echoreq.c -o echoreq

echod: echod.c
	$(CC) $(CFLAGS) echod.c -o echod

echoreq2: echoreq2.c
	$(CC) $(CFLAGS) echoreq2.c -o echoreq2
